### ISSUE TITLE
Getting All Of The Closest Colours To A Pacific Colour 

### ISSUE THREAD

**Issue by andreweberle** [smchughinfo/color#1]
G'day, Thanks for your help so far, however I was wonder with the code you have provided.

So far I have been able to scan each pixel of the picture, however with the `getname()` function, I having trouble getting all the colours that are similar to violet, or violet shades.  

Is this something that this code can help me with?

Thanks again.

**Comment by smchughinfo** [comment]
I think so.

I think what you would do is use the code in getname() to find the distance between the color of each pixel and the color violet. Then you can just set a threshold for the distance.

**Comment by andreweberle** [comment]
Cheers :)
